sonar.projectKey=Neha-Bai_cohort-9-mern-14020-neha
sonar.organization=neha-bai
sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/test/**
sonar.tests=backend/test
sonar.test.inclusions=**/*.test.js